name: Trigger Playwright Tests

on:
  push:
    branches: [ develop, task/tcr/7.2-work]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.PAT }}
        repository: TCRodriguez/training-mode-playwright-automation-repo
        event-type: trigger-playwright-tests
